
---
AWSTemplateFormatVersion: "2010-09-09"
Description: "CloudFormation template with Ansible variable"


Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: "{{ VpcCidrBlock }}"  # cfn-lint:ignore=E1010

      EnableDnsSupport: true
      EnableDnsHostnames: true
      InstanceTenancy: default
     
