---
AWSTemplateFormatVersion: "2010-09-09"
Description: "CloudFormation template with Ansible variable"

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: "{{ VpcCidrBlock }}"  # cfn-lint:ignore=E3031

      EnableDnsSupport: true
      EnableDnsHostnames: true
      InstanceTenancy: default
      
  AnotherVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: "{{ AnotherVpcCidrBlock }}"
      EnableDnsSupport: true
      EnableDnsHostnames: true
      InstanceTenancy: default
     

Metadata:
  cfn-lint:
    config:
      ignore_checks:
        - E3031
