AWSTemplateFormatVersion: "2010-09-09"

Description: cnew

Resources:
  EBSVolume:    
    Type: "AWS::EC2::Volume"
    Properties:
      Encrypted: true
      exclude_this_line
      AvailabilityZone: us-east-1a
      Size: 100
