
---
AWSTemplateFormatVersion: "2010-09-09"
Description: "CloudFormation template with Ansible variable"

Resources:
  MyBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: "{{ MyParameter }}"
