
---
AWSTemplateFormatVersion: "2010-09-09"
Description: "CloudFormation template with Ansible variable"

Parameters:
  VpcCidrBlock:
    Type: String
    Default: "10.0.0.0/16"
    Description: "The CIDR block for the VPC"

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: "{{ VpcCidrBlock }}"
      EnableDnsSupport: true
      EnableDnsHostnames: true
      InstanceTenancy: default
      Tags:
        - Key: Environment
          Value: !Ref Environment
